### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by Irenedan** [megaacheyounes/rn-geolocation-inclusive#1]
Hello,
I noticed that you have used the ACCESS_FINE_LOCATION permission, and I have some related issues, could you help me if you have time?

I used:
PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION)
But the function returns never_ask_again when I hit the back button on my phone(or click on the blank). is there any way to deal with this wrong status?
Looks like this: https://github.com/facebook/react-native/issues/30158

**Comment by megaacheyounes** [comment]
Hi Irene,

This issue is beyond the scope of this demo, but if you can't ask for permission again after pressing the back button, then you can redirect users to your app's settings page (see https://reactnative.dev/docs/linking#opensettings ) where the user will grant the permission manually

You may also consider using a library for better permission handling, like this one:  https://github.com/zoontek/react-native-permissions

**Comment by Irenedan** [comment]
> Hi Irene,
> 
> This issue is beyond the scope of this demo, but if you can't ask for permission again after pressing the back button, then you can redirect users to your app's settings page (see https://reactnative.dev/docs/linking#opensettings ) where the user will grant the permission manually
> 
> You may also consider using a library for better permission handling, like this one: https://github.com/zoontek/react-native-permissions

Okay, thank you for your reply.
